#!/bin/sh
# Generated by build/assemble.py. Edit the assembler, not this file.
exec sh "${CLAUDE_PLUGIN_ROOT}/engines/fiction-host/claude_code_gate/run_hook.sh" "${CLAUDE_PLUGIN_ROOT}/engines/fiction-host/claude_code_gate/gate_prompt_hook.py" --scene-skill "curse-of-aestrum:scene"
