#!/bin/sh
# Generated by build/assemble.py. Edit the assembler, not this file.
exec sh "${CLAUDE_PLUGIN_ROOT}/engines/fiction-host/claude_code_gate/run_hook.sh" "${CLAUDE_PLUGIN_ROOT}/engines/fiction-host/claude_code_gate/gate_stop_hook.py" --scene-skill "curse-of-aestrum:scene" --spec "${CLAUDE_PLUGIN_ROOT}/engines/prose-engine/scene/gate/infrastructure_tokens.toml" --spec "${CLAUDE_PLUGIN_ROOT}/engines/rpg-5e-engine/rules/player_meta_tokens.toml" --spec "${CLAUDE_PLUGIN_ROOT}/overrides/gate_lint/forbidden_tokens.toml"
