#!/bin/sh
# Generated by build/assemble.py. Edit the assembler, not this file.
exec sh "${CLAUDE_PLUGIN_ROOT}/engines/fiction-host/claude_code_gate/run_hook.sh" "${CLAUDE_PLUGIN_ROOT}/engines/fiction-host/claude_code_gate/staging_stop_hook.py" --scene-skill "curse-of-aestrum:scene" --staging-glob "${CLAUDE_PROJECT_DIR}/campaign_state/*/staging/*.md"
